name: Build CBL-Mariner Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with: 
          repository: 'microsoft/CBL-Mariner'
          ref: '1.0-stable'
          
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
        
      - name: Install Remaining Prerequisites
        run: |
          sudo apt-get update
          sudo apt -y install make tar wget curl rpm qemu-utils genisoimage pigz
          
      - name: ISO Quick Start
        run: |
          pushd toolkit
          sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
          popd
      
      - name: Upload the iso image
        uses: actions/upload-artifact@v2
        if: success()  # upload iso only if previous steps are successful.
        with:
          name: CBL-Mariner
          path: out/images/full/*.iso
